
#
# Spring 配置
#
spring:
  devtools:
    restart:
      enabled: false

  datasource:
    url: jdbc:mysql://bullet-server:3306/db_bullet?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: ${BULLET_MYSQL_PASSWORD:123456}


