
#
# Spring 配置
#
spring:
  profiles:
    active: dev
  application:
    name: bullet
    admin:
      enabled: true
  devtools:
    restart:
      enabled: true



security:
  basic:
    enabled: false
management:
  security:
    enabled: false


# log config
logging:
  config: 'classpath:logback-spring.xml'
